publishDir = "../../docs"

author = "Panjie Setiawan Wicaksono"
baseURL = "https://https://panjiesw.github.io/frest/"
languageCode = "en-us"
defaultContentLanguage = "en"

title = "Frest Documentation"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

pygmentsCodeFences = true
pygmentsOptions = "linenos=table"
pygmentsStyle = "dracula"

[params]
description = "Frest is easy to use browser REST client wrapper for Fetch API with interceptor feature and XMLHttpRequest fallback for download, upload and when Fetch API is not available."
editURL = "https://github.com/panjiesw/frest/edit/master/internal/docs/content/"
author = "Panjie Setiawan Wicaksono"
showVisitedLinks = true
themeVariant = "frest"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Documentation for Frest"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/panjiesw/frest"
weight = 10
